export const PERFORM_SEARCH = 'PERFORM_SEARCH'
export const PERFORM_SEARCH_SUCCESS = 'PERFORM_SEARCH_SUCCESS'
export const PERFORM_SEARCH_ERROR = 'PERFORM_SEARCH_ERROR'

export const START_LOAD = 'START_LOAD';
export const STOP_LOAD = 'STOP_LOAD';
export const LOGGED_IN = 'LOGGED_IN';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGIN_START = 'LOGIN_START'
// export const LOGGED_IN = 'LOGGED_IN'

// export const LOGOUT_START = 'LOGOUT_START'
// export const LOGGED_OUT = 'LOGGED_OUT'

// export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOAD_ALL_USER_DATA_PENDING = 'LOAD_ALL_USER_DATA_PENDING'
export const LOAD_ALL_USER_DATA_SUCCESS = 'LOAD_ALL_USER_DATA_SUCCESS'
export const LOAD_ALL_USER_DATA_ERROR = 'LOAD_ALL_USER_DATA_ERROR'

export const FETCH_OWNERS_PENDING = 'FETCH_OWNERS_PENDING';
export const FETCH_OWNERS_SUCCESS = 'FETCH_OWNERS_SUCCESS';
export const FETCH_OWNERS_ERROR = 'FETCH_OWNERS_ERROR';




